export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const CLEAR_STATE = "CLEAR_STATE";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const PREV_PASSWORD = "PREV_PASSWORD";