// Get PERMISSION data
export const ALL_PERMISSION_REQUEST_BY_USER = "ALL_PERMISSION_REQUEST_BY_USER";
export const ALL_PERMISSION_SUCCESS_BY_USER = "ALL_PERMISSION_SUCCESS_BY_USER";
export const ALL_PERMISSION_FAILED_BY_USER = "ALL_PERMISSION_FAILED_BY_USER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
